"""Emit the web app's brand components from the traced artwork.

    tools/brand-gold/.venv/bin/python tools/brand-gold/emit_tsx.py

Called by sync.sh. Inlining beats <img src="/brand/logo.svg"> here: the lockup is
charcoal + gold, so the letterforms need currentColor to follow the app's light/dark
text colour, and inlining avoids a second request behind the service worker.
"""
import os
import re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SVG = os.path.join(ROOT, "brand", "bime-gold", "traced", "svg")
DST = os.path.join(ROOT, "apps", "web", "src", "components")

COMPONENTS = [
    ("BrandLogo", "logo.svg", "بیمه گلد", """/**
 * The full Bime Gold lockup. This is the default — use it anywhere it fits.
 * `bime` is `currentColor`, so set the colour with a text utility; `gold` and the
 * tittle are always brand gold. Wider than tall — size it with a height, e.g. `h-7 w-auto`.
 */"""),
    ("BrandMark", "mark.svg", "بیمه گلد", """/**
 * The lockup reduced to `bi` plus the gold tittle. Only for places the full lockup
 * cannot be read — favicons and anything under about 48px. Prefer {@link BrandLogo}.
 * Taller than wide — size it with a height, e.g. `h-9 w-auto`.
 */"""),
]

for name, src, label, doc in COMPONENTS:
    svg = open(os.path.join(SVG, src)).read()
    view = re.search(r'viewBox="([^"]+)"', svg).group(1)
    inner = re.sub(r"^.*?<svg[^>]*>|</svg>\s*$", "", svg, flags=re.S)
    inner = inner.replace('fill="#2B2B2B"', 'fill="currentColor"')
    inner = inner.replace("fill-rule=", "fillRule=")
    path = os.path.join(DST, f"{name}.tsx")
    open(path, "w").write(
        f"""// GENERATED by tools/brand-gold/emit_tsx.py — do not edit.
// Source: brand/bime-gold/traced/svg/{src}. Re-run tools/brand-gold/build.sh.

{doc}
export const {name} = ({{ className }}: {{ className?: string }}) => (
  <svg viewBox="{view}" className={{className}} role="img" aria-label="{label}">
    {inner.strip()}
  </svg>
)
"""
    )
    print("wrote", path)
