"""Emit the web app's BrandMark component from the traced mark artwork.

    tools/brand-gold/.venv/bin/python tools/brand-gold/emit_tsx.py

Called by sync.sh. Inlining beats <img src="/brand/mark.svg"> here: the mark is
charcoal + gold, so it needs currentColor for the letterforms to follow the app's
light/dark text colour, and inlining avoids a second request behind the service worker.
"""
import os
import re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SRC = os.path.join(ROOT, "brand", "bime-gold", "traced", "svg", "mark.svg")
DST = os.path.join(ROOT, "apps", "web", "src", "components", "BrandMark.tsx")

svg = open(SRC).read()
view = re.search(r'viewBox="([^"]+)"', svg).group(1)
inner = re.sub(r"^.*?<svg[^>]*>|</svg>\s*$", "", svg, flags=re.S)
# The letterforms follow the app's text colour; the tittle is always brand gold.
inner = inner.replace('fill="#2B2B2B"', 'fill="currentColor"')
inner = inner.replace("fill-rule=", "fillRule=")

open(DST, "w").write(f"""// GENERATED by tools/brand-gold/emit_tsx.py — do not edit.
// Source: brand/bime-gold/traced/svg/mark.svg. Re-run tools/brand-gold/build.sh.

/**
 * The Bime Gold mark: lowercase `bi` lifted from the wordmark, with the gold tittle.
 * The letterforms are `currentColor`, so set the colour with a text utility.
 * Aspect ratio is taller than wide — size it with a height, e.g. `h-9 w-auto`.
 */
export const BrandMark = ({{ className }}: {{ className?: string }}) => (
  <svg viewBox="{view}" className={{className}} role="img" aria-label="بیمه گلد">
    {inner.strip()}
  </svg>
)
""")
print("wrote", DST)
