"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VEHICLE_MODELS = void 0;
exports.VEHICLE_MODELS = [
    // ── ایران خودرو ──────────────────────────────────────────────────────────
    { brandFa: 'ایران خودرو', modelFa: 'پژو ۲۰۶', group: 'SEDAN' },
    { brandFa: 'ایران خودرو', modelFa: 'پژو ۲۰۶ صندوق‌دار', group: 'SEDAN' },
    { brandFa: 'ایران خودرو', modelFa: 'پژو ۲۰۷', group: 'SEDAN' },
    { brandFa: 'ایران خودرو', modelFa: 'پژو ۳۰۱', group: 'SEDAN' },
    { brandFa: 'ایران خودرو', modelFa: 'پژو ۴۰۵', group: 'SEDAN' },
    { brandFa: 'ایران خودرو', modelFa: 'پژو پارس', group: 'SEDAN' },
    { brandFa: 'ایران خودرو', modelFa: 'پژو روآ', group: 'SEDAN' },
    { brandFa: 'ایران خودرو', modelFa: 'پیکان', group: 'SEDAN' },
    { brandFa: 'ایران خودرو', modelFa: 'سمند', group: 'SEDAN' },
    { brandFa: 'ایران خودرو', modelFa: 'سمند سورن', group: 'SEDAN' },
    { brandFa: 'ایران خودرو', modelFa: 'سمند سورن پلاس', group: 'SEDAN' },
    { brandFa: 'ایران خودرو', modelFa: 'دنا', group: 'SEDAN' },
    { brandFa: 'ایران خودرو', modelFa: 'دنا پلاس', group: 'SEDAN' },
    { brandFa: 'ایران خودرو', modelFa: 'رانا', group: 'SEDAN' },
    { brandFa: 'ایران خودرو', modelFa: 'رانا پلاس', group: 'SEDAN' },
    { brandFa: 'ایران خودرو', modelFa: 'تارا', group: 'SEDAN' },
    { brandFa: 'ایران خودرو', modelFa: 'ری‌را', group: 'SEDAN' },
    { brandFa: 'ایران خودرو', modelFa: 'هایما S5', group: 'SEDAN' },
    { brandFa: 'ایران خودرو', modelFa: 'هایما S7', group: 'SEDAN' },
    { brandFa: 'ایران خودرو', modelFa: 'هایما ۸S', group: 'SEDAN' },
    { brandFa: 'ایران خودرو', modelFa: 'وانت آریسان', group: 'PICKUP' },
    { brandFa: 'ایران خودرو', modelFa: 'وانت پیکان', group: 'PICKUP' },
    // ── سایپا ────────────────────────────────────────────────────────────────
    { brandFa: 'سایپا', modelFa: 'پراید ۱۱۱', group: 'SEDAN' },
    { brandFa: 'سایپا', modelFa: 'پراید ۱۳۱', group: 'SEDAN' },
    { brandFa: 'سایپا', modelFa: 'پراید ۱۳۲', group: 'SEDAN' },
    { brandFa: 'سایپا', modelFa: 'پراید ۱۴۱', group: 'SEDAN' },
    { brandFa: 'سایپا', modelFa: 'پراید صبا', group: 'SEDAN' },
    { brandFa: 'سایپا', modelFa: 'تیبا', group: 'SEDAN' },
    { brandFa: 'سایپا', modelFa: 'تیبا ۲', group: 'SEDAN' },
    { brandFa: 'سایپا', modelFa: 'ساینا', group: 'SEDAN' },
    { brandFa: 'سایپا', modelFa: 'ساینا S', group: 'SEDAN' },
    { brandFa: 'سایپا', modelFa: 'کوییک', group: 'SEDAN' },
    { brandFa: 'سایپا', modelFa: 'کوییک R', group: 'SEDAN' },
    { brandFa: 'سایپا', modelFa: 'کوییک S', group: 'SEDAN' },
    { brandFa: 'سایپا', modelFa: 'شاهین', group: 'SEDAN' },
    { brandFa: 'سایپا', modelFa: 'آریا', group: 'SEDAN' },
    { brandFa: 'سایپا', modelFa: 'اطلس', group: 'SEDAN' },
    { brandFa: 'سایپا', modelFa: 'چانگان CS35', group: 'SEDAN' },
    { brandFa: 'سایپا', modelFa: 'وانت نیسان', group: 'PICKUP' },
    { brandFa: 'سایپا', modelFa: 'وانت زامیاد', group: 'PICKUP' },
    { brandFa: 'سایپا', modelFa: 'وانت پادرا', group: 'PICKUP' },
    { brandFa: 'سایپا', modelFa: 'وانت پراید ۱۵۱', group: 'PICKUP' },
    // ── مدیران خودرو (چری / ام‌وی‌ام / فونیکس) ────────────────────────────────
    { brandFa: 'مدیران خودرو', modelFa: 'چری آریزو ۵', group: 'SEDAN' },
    { brandFa: 'مدیران خودرو', modelFa: 'چری آریزو ۶', group: 'SEDAN' },
    { brandFa: 'مدیران خودرو', modelFa: 'چری تیگو ۵', group: 'SEDAN' },
    { brandFa: 'مدیران خودرو', modelFa: 'چری تیگو ۷', group: 'SEDAN' },
    { brandFa: 'مدیران خودرو', modelFa: 'چری تیگو ۸', group: 'SEDAN' },
    { brandFa: 'مدیران خودرو', modelFa: 'فونیکس آریزو ۶ پرو', group: 'SEDAN' },
    { brandFa: 'مدیران خودرو', modelFa: 'فونیکس تیگو ۸ پرو', group: 'SEDAN' },
    { brandFa: 'مدیران خودرو', modelFa: 'ام‌وی‌ام ۱۱۰', group: 'SEDAN' },
    { brandFa: 'مدیران خودرو', modelFa: 'ام‌وی‌ام ۳۱۵', group: 'SEDAN' },
    { brandFa: 'مدیران خودرو', modelFa: 'ام‌وی‌ام ۵۵۰', group: 'SEDAN' },
    { brandFa: 'مدیران خودرو', modelFa: 'ام‌وی‌ام X22', group: 'SEDAN' },
    { brandFa: 'مدیران خودرو', modelFa: 'ام‌وی‌ام X33', group: 'SEDAN' },
    { brandFa: 'مدیران خودرو', modelFa: 'ام‌وی‌ام X55', group: 'SEDAN' },
    // ── کرمان موتور ──────────────────────────────────────────────────────────
    { brandFa: 'کرمان موتور', modelFa: 'جک J4', group: 'SEDAN' },
    { brandFa: 'کرمان موتور', modelFa: 'جک J5', group: 'SEDAN' },
    { brandFa: 'کرمان موتور', modelFa: 'جک S3', group: 'SEDAN' },
    { brandFa: 'کرمان موتور', modelFa: 'جک S5', group: 'SEDAN' },
    { brandFa: 'کرمان موتور', modelFa: 'جک K7', group: 'SEDAN' },
    { brandFa: 'کرمان موتور', modelFa: 'لیفان ۶۲۰', group: 'SEDAN' },
    { brandFa: 'کرمان موتور', modelFa: 'لیفان X60', group: 'SEDAN' },
    { brandFa: 'کرمان موتور', modelFa: 'کی‌ام‌سی J7', group: 'SEDAN' },
    { brandFa: 'کرمان موتور', modelFa: 'کی‌ام‌سی T8', group: 'PICKUP' },
    // ── بهمن موتور ───────────────────────────────────────────────────────────
    { brandFa: 'بهمن موتور', modelFa: 'دیگنیتی', group: 'SEDAN' },
    { brandFa: 'بهمن موتور', modelFa: 'فیدلیتی', group: 'SEDAN' },
    { brandFa: 'بهمن موتور', modelFa: 'ریسپکت', group: 'SEDAN' },
    { brandFa: 'بهمن موتور', modelFa: 'کارا', group: 'PICKUP' },
    { brandFa: 'بهمن موتور', modelFa: 'کاپرا', group: 'PICKUP' },
    { brandFa: 'بهمن موتور', modelFa: 'وانت مزدا', group: 'PICKUP' },
    // ── رنو ──────────────────────────────────────────────────────────────────
    { brandFa: 'رنو', modelFa: 'ال۹۰', group: 'SEDAN' },
    { brandFa: 'رنو', modelFa: 'پارس تندر', group: 'SEDAN' },
    { brandFa: 'رنو', modelFa: 'ساندرو', group: 'SEDAN' },
    { brandFa: 'رنو', modelFa: 'ساندرو استپ‌وی', group: 'SEDAN' },
    { brandFa: 'رنو', modelFa: 'مگان', group: 'SEDAN' },
    // ── وارداتی ──────────────────────────────────────────────────────────────
    { brandFa: 'تویوتا', modelFa: 'کرولا', group: 'SEDAN' },
    { brandFa: 'تویوتا', modelFa: 'کمری', group: 'SEDAN' },
    { brandFa: 'تویوتا', modelFa: 'راو ۴', group: 'SEDAN' },
    { brandFa: 'تویوتا', modelFa: 'پرادو', group: 'SEDAN' },
    { brandFa: 'تویوتا', modelFa: 'هایلوکس', group: 'PICKUP' },
    { brandFa: 'هیوندای', modelFa: 'النترا', group: 'SEDAN' },
    { brandFa: 'هیوندای', modelFa: 'سوناتا', group: 'SEDAN' },
    { brandFa: 'هیوندای', modelFa: 'اکسنت', group: 'SEDAN' },
    { brandFa: 'هیوندای', modelFa: 'توسان', group: 'SEDAN' },
    { brandFa: 'هیوندای', modelFa: 'i20', group: 'SEDAN' },
    { brandFa: 'کیا', modelFa: 'سراتو', group: 'SEDAN' },
    { brandFa: 'کیا', modelFa: 'اپتیما', group: 'SEDAN' },
    { brandFa: 'کیا', modelFa: 'اسپورتیج', group: 'SEDAN' },
    { brandFa: 'کیا', modelFa: 'ریو', group: 'SEDAN' },
    { brandFa: 'کیا', modelFa: 'پیکانتو', group: 'SEDAN' },
    { brandFa: 'مزدا', modelFa: 'مزدا ۳', group: 'SEDAN' },
    { brandFa: 'مزدا', modelFa: 'مزدا ۲', group: 'SEDAN' },
    { brandFa: 'نیسان', modelFa: 'ماکسیما', group: 'SEDAN' },
    { brandFa: 'نیسان', modelFa: 'جوک', group: 'SEDAN' },
    // ── ون و مینی‌بوس ────────────────────────────────────────────────────────
    { brandFa: 'هیوندای', modelFa: 'مینی‌بوس کروز', group: 'VAN' },
    { brandFa: 'بنز', modelFa: 'مینی‌بوس ۳۰۹', group: 'VAN' },
    { brandFa: 'ایویکو', modelFa: 'مینی‌بوس', group: 'VAN' },
    { brandFa: 'فوتون', modelFa: 'ون', group: 'VAN' },
    { brandFa: 'سایپا', modelFa: 'ون کاروان', group: 'VAN' },
    // ── کامیون و کامیونت ─────────────────────────────────────────────────────
    { brandFa: 'بنز', modelFa: 'کامیون ۱۹۲۴', group: 'TRUCK' },
    { brandFa: 'بنز', modelFa: 'اکتروس', group: 'TRUCK' },
    { brandFa: 'ایویکو', modelFa: 'کامیونت', group: 'TRUCK' },
    { brandFa: 'فوتون', modelFa: 'کامیونت', group: 'TRUCK' },
    { brandFa: 'ایسوزو', modelFa: 'کامیونت', group: 'TRUCK' },
    { brandFa: 'هوو', modelFa: 'کامیون', group: 'TRUCK' },
    { brandFa: 'کاماز', modelFa: 'کامیون', group: 'TRUCK' },
    // ── موتورسیکلت ───────────────────────────────────────────────────────────
    { brandFa: 'هوندا', modelFa: 'CG125', group: 'MOTORCYCLE' },
    { brandFa: 'هوندا', modelFa: 'CDI125', group: 'MOTORCYCLE' },
    { brandFa: 'کویر موتور', modelFa: 'KMC 200', group: 'MOTORCYCLE' },
    { brandFa: 'کویر موتور', modelFa: 'KMC 250', group: 'MOTORCYCLE' },
    { brandFa: 'باجاج', modelFa: 'پالس', group: 'MOTORCYCLE' },
    { brandFa: 'تی‌وی‌اس', modelFa: 'آپاچی', group: 'MOTORCYCLE' },
    { brandFa: 'احسان', modelFa: 'موتورسیکلت', group: 'MOTORCYCLE' },
    { brandFa: 'دینو', modelFa: 'موتورسیکلت', group: 'MOTORCYCLE' },
    { brandFa: 'نامی', modelFa: 'موتورسیکلت برقی', group: 'MOTORCYCLE' },
];
//# sourceMappingURL=vehicle-models.js.map